### ISSUE TITLE
Retrofit Post Method

### ISSUE THREAD

**Issue by ahmed-zedan** [octav8us/KreazTanta#6]
### Code
https://github.com/octav8us/KreazTanta/blob/58d3d728410039216910d4c5d424bbe045cf24a8/app/src/main/java/com/example/kreaz/network/ApiService.kt#L32:L37

### Review
This link must be crash because the HTTP method is a POST.

#### Reference
- [Retrofit - Request Body](https://square.github.io/retrofit/)
- [Send Data Form-Urlencoded](https://futurestud.io/tutorials/retrofit-send-data-form-urlencoded)

#### mentions
@octav8us

**Comment by octav8us** [comment]
![Screenshot_2021-08-30-22-47-37-41](https://user-images.githubusercontent.com/86563979/131403493-43f0d39b-f327-4fd7-992d-bb3cbbd873ba.jpg)
This is what last commit is like 
Not sure why you see the old code.

**Comment by octav8us** [comment]
@POST("index.php")
    @FormUrlEncoded
    suspend fun postToCart(
        @Query("mode") mode: String = "set",
        @Query("type") type: String = "addtocart",
        @Field("items") items: String,
        @Field("name") name: String,
        @Field("mobile") mobile: String
    ): CartOrderResponse

**Comment by ahmed-zedan** [comment]
Nice Work.
